# Generated by Django 2.1.5 on 2019-02-01 02:54

from django.db import migrations


def add_view_verb(apps, schema):
    Verb = apps.get_model('ana', 'Verb')
    Verb.objects.create(slug='page-view')


def backwards(apps, schema):
    Verb = apps.get_model('ana', 'Verb')
    Verb.objects.get(slug='page-view').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ana', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_view_verb, backwards),
    ]
