# Generated by Django 2.1.5 on 2019-02-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ana', '0002_initial_verbs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['pk'], 'permissions': (('can_access_ana_api_analytics', 'Can access analytics api'), ('can_access_ana_dashboard', 'Can view analytics dashboard'))},
        ),
    ]
